config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  resources :bookings, only: [:index, :edit, :update]
  post "/bookings/:id/confirm", to: "bookings#confirm", as: "confirm"
  resources :meals, only: [:index, :new, :show, :create] do
    resources :bookings, only: [:new, :create, :destroy]
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :bookings
  has_many :meals
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, omniauth_providers: [:facebook, :google_oauth2]


  # after_create :subscribe_to_newsletter, :send_welcome_email
  after_create :send_welcome_email


   def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
      return user
    end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(
           first_name: data["first_name"],
           last_name: data["last_name"],
           facebook_picture_url: data["image"],
           email: data["email"],
           password: Devise.friendly_token[0,20],
        )
    end
    user
  end

  private


  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver_now

  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

   def google_oauth2
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    now = Time.now
    @user = User.find(params[:id])
    @bookings = @user.bookings.order(date: :desc)
    @booked = []
    @user.meals.each do |meal|
      mealid = meal.id
      @booked << Booking.where(meal_id: mealid)
    end

    @booked.flatten!
    @booked.each do |book|
      if (book.date < now)
        book.status = "Passed"
      end
    end
    @booked.sort_by {|book| book.date.to_i}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/users/new.html.erb
<!--
  Code: https://github.com/lewagon/google-maps-markers-static
-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Google Maps Markers - Static Example</title>
    <style type="text/css">
      body { margin: 0; }
      #map {
        display: flex;
        height: 100vh;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <!-- The map will be drawn in this div -->
    <div id="map"></div>

    <!-- Include Google Maps JS library. You should use your *own* key -->
    <script src="https://maps.google.com/maps/api/js?key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU"></script>

    <!-- Include Dependencies of GMaps for Rails gem -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js"></script>
    <script src="https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"></script>
    <script src="https://cdn.rawgit.com/apneadiving/Google-Maps-for-Rails/master/js_compilation/gmaps_google.js"></script>

    <script type="text/javascript">
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers([
            {
              "lat": 43.3027392,
              "lng": 5.3765816,
              "infowindow": "<h1>Aix - Marseille</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/008/thumbnail/marseille.jpg?1445520529' height='200'></p>"
            },
            {
              "lat": 52.3431438,
              "lng": 4.8291689,
              "infowindow": "<h1>Amsterdam</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/011/thumbnail/amsterdam.jpg?1453219893' height='200'></p>"
            },
            {
              "lat": 33.8937913,
              "lng": 35.5017767,
              "infowindow": "<h1>Beirut</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/004/thumbnail/beirut.jpg?1445520746' height='200'></p>"
            },
            {
              "lat": -19.9156207,
              "lng": -43.9345931,
              "infowindow": "<h1>Belo Horizonte</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/018/thumbnail/BH.jpg?1467361247' height='200'></p>"
            },
            {
              "lat": 44.8418706,
              "lng": -0.5706669,
              "infowindow": "<h1>Bordeaux</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/005/thumbnail/bordeaux.jpg?1445962618' height='200'></p>"
            },
            {
              "lat": 50.8474433,
              "lng": 4.3591849,
              "infowindow": "<h1>Brussels</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/002/thumbnail/brussels.jpg?1445520592' height='200'></p>"
            },
            {
              "lat": 55.699662,
              "lng": 12.532918,
              "infowindow": "<h1>Copenhagen</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/013/thumbnail/k%C3%B8benhavn-bg.jpg?1454509826' height='200'></p>"
            },
            {
              "lat": 50.6333542,
              "lng": 3.0203766,
              "infowindow": "<h1>Lille</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/003/thumbnail/lille.jpg?1445520692' height='200'></p>"
            },
            {
              "lat": 38.7324346,
              "lng": -9.1423852,
              "infowindow": "<h1>Lisbon</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/009/thumbnail/8130866554_0faf8af6e6_k.jpg?1447424100' height='200'></p>"
            },
            {
              "lat": 51.5213244,
              "lng": -0.0766771,
              "infowindow": "<h1>London</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/014/thumbnail/2722715933_ed5a01fa23_o.jpg?1457434940' height='200'></p>"
            },
            {
              "lat": 45.764043,
              "lng": 4.835659,
              "infowindow": "<h1>Lyon</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/016/thumbnail/1024px-Lyon_basilique_de_fourvie%CC%80re.jpg?1463049986' height='200'></p>"
            },
            {
              "lat": 47.218371,
              "lng": -1.553621,
              "infowindow": "<h1>Nantes</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/012/thumbnail/nantes.jpg?1453388206' height='200'></p>"
            },
            {
              "lat": 48.8648482,
              "lng": 2.3798534,
              "infowindow": "<h1>Paris</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/001/thumbnail/15079403417_371f698d27_k.jpg?1445521241' height='200'></p>"
            },
            {
              "lat": -22.97754,
              "lng": -43.234288,
              "infowindow": "<h1>Rio de Janeiro</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/019/thumbnail/rio_1.jpg?1469439835' height='200'></p>"
            },
            {
              "lat": -23.5591728,
              "lng": -46.6801402,
              "infowindow": "<h1>São Paulo</h1><p><img src='https://d1gofzrmx0fcbg.cloudfront.net/production/cities/city_pictures/000/000/015/thumbnail/12280389883_aecfecfc0e_h.jpg?1458582747' height='200'></p>"
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
    </script>
  </body>
</html>

<!--
Ruby script which generated the markers from lewagon/alumni repo:
require "json"
markers = []
City.order(:name).each do |city|
  if city.latitude && city.longitude
    markers << {
      lat: city.latitude,
      lng: city.longitude,
      infowindow: "<h1>#{city.name}</h1><p><img src='#{city.city_picture.url(:thumbnail)}' height='200'></p>"
    }
  end
end
puts JSON.pretty_generate(markers)
-->

app/views/users/show.html.erb
<div class="banner-backgroundonly", style="background-color: linear-gradient(100deg, rgba(257,257,257,0.1) 20%, rgba(0,0,0,0.9) 50%))" >
  <div class="dash-banner ">
    <div class="container">

      <div class="row">

        <div class="col-xs-12 col-sm-6 text-center">
          <h1 class="thin-title">My bookings as a <span>Host</span><h1>
          <!-- <div class="img-container"> -->
            <%= image_tag("meal.png", id: "customer", class: "img-dash")  %>
          <!-- </div> -->
        </div>

        <div class="col-xs-12 col-sm-6 text-center">
          <h1 class="thin-title">My bookings as a <span>Chef</span><h1>
          <!-- <div class="img-container"> -->
            <%= image_tag("chef.png", id: "chief", class: "img-dash")%>
          <!-- </div> -->
        </div>

      </div>

    </div>
  </div>
</div>

<div class="chief-dash invisible">
  <div class="container">
    <div class="row">
      <div class="booking-content">
        <div class=" col-xs-12">
          <h2>I will cook for...</h2>
          <table class = "table">
          <thead>
            <tr>
              <th>Host</th>
              <th>Email</th>
              <th>Meal</th>
              <th>Guests #</th>
              <th>Date</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody >
            <% @booked.each do |booking| %>
              <tr>
                <td class="hand-font bold"><%= booking.user.first_name + " " + booking.user.last_name %></td>
                <td><%= booking.user.email %></td>
                <td><%= booking.meal.name %></td>
                <td><%= booking.number_customers %></td>
                <td><%= booking.date.strftime("%d/%m/%Y") %></td>
                <td>
                  <% if booking.status != "Confirmed" %>
                    <span><%= "Pending" %></span>
                  <% else %>
                    <span class="red-text"><%= "Confirmed" %></span>
                  <% end %>
                </td>

                <td><%= link_to 'Cancel', meal_booking_path(@user, booking),class: "btn-transparent", method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td><%= link_to 'Validate', confirm_path(booking), method: :post, class: "btn btn-success" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Back to meals',  meals_path, :class => "btn btn-primary "%>
        <%= link_to 'Back to dashboard',  user_path(current_user), :class => "btn btn-transparent-red "%>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

<div class="customer-dash invisible">
  <div class="container">
    <div class="row">
      <div class="booking-content">
        <div class="col-xs-12">
          <h2>I will eat with...</h2>
          <table class = "table">
          <thead>
            <tr>
              <th>Chef</th>
              <th>Email</th>
              <th>Meal</th>
              <th>Guests #</th>
              <th>Date</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody >
            <% @bookings.each do |booking| %>
              <tr>
                <td class="hand-font bold"><%= booking.meal.user.first_name + " " + booking.meal.user.last_name %></td>
                <td><%= booking.meal.user.email %></td>
                <td><%= booking.meal.name %></td>
                <td><%= booking.number_customers %></td>
                <td><%= booking.date.strftime("%d/%m/%Y") %></td>
                 <td>
                  <% if booking.status != "Confirmed" %>
                    <span><%= "Pending" %></span>
                  <% elsif booking.status == "Passed"%>
                    <span class="green-text"><%= "Passed" %></span>
                  <% else %>
                    <span class="red-text"><%= "Confirmed" %></span>
                  <% end %>
                </td>
                <td><%= link_to 'Cancel', meal_booking_path(@user, booking),class: "btn btn-transparent", method: :delete, data: { confirm: 'Do you really want to cancel the booking ?' } %></td>
               <!--  -->
              </tr>

            <% end %>
          </tbody>
        </table>
          <%= link_to 'Back to meals',  meals_path, :class => "btn btn-primary "%>
          <%= link_to 'Back to dashboard',  user_path(current_user), :class => "btn btn-transparent-red "%>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>